### PR TITLE
Fix test by removing override function's private access controls

### PR DESCRIPTION
**Pull request by jasonnam**

### CODE REVIEW

**Comment by jflinter** [comment]
Can you explain this change a bit more?

**Comment by bm-w** [comment]
Ran into this as well: Xcode 8.1 GM seed (8T61a) gives errors for these overridden methods:
```
Dwifft/DwifftTests/DwifftTests.swift:73:35: Overriding instance method must be as accessible as its enclosing type
```

**Comment by jflinter** [comment]
thanks @jasonnam and @bm-w; sorry for the slow merge.

**Comment by Bogidon** [comment]
@jflinter can you make a new release with this, so Dwifft can compile on Xcode 8.1 / Swift 3.0.1? Probably should also merge https://github.com/jflinter/Dwifft/pull/36 once Travis supports Xcode 8.1: https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-version

**Pull request merged**
