### PR TITLE
Update to Xcode 8.1 and Swift 3.0.1

### PR DESCRIPTION
**Pull request by bm-w**
Compiles on Xcode 8.1 GM seed (8T61a).

### CODE REVIEW

**Comment by Bogidon** [comment]
Travis doesn't yet support Xcode 8.1: https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-version

**Comment by FranciscoAmado** [comment]
This would also help with the Carthage build as in #40

**Comment by jflinter** [comment]
Given that Travis doesn't support Xcode 8.1 yet, I've fixed this on a separate branch. Version 0.5 now supports Swift 3.0.1/Xcode 8. Thanks for opening.

**Comment by bm-w** [comment]
Sorry, I might have commented on this in more detail to save you the trouble of figuring out what my intent here was—but @FranciscoAmado got it! 😉

Oh, and I hadn't realized pre-8.1 Xcode versions would accept the Swift version 3.0.1 setting!

**Comment by bm-w** [comment]
FYI: [The Travis CI Blog: Xcode 8.1 is here!](https://blog.travis-ci.com/2016-11-15-xcode-81-is-here).

**Pull request closed without merging**
