### PR TITLE
Converted project to swift 2.3

### PR DESCRIPTION
**Pull request by regynald**

### CODE REVIEW

**Comment by jflinter** [comment]
For my sanity (and that of others using Xcode 7), I'm going to hold off on merging this until Xcode 8 is out of beta.

**Comment by jflinter** [comment]
But thanks @regynald!

**Comment by IvoPintodaSilva** [comment]
Now that the Xcode GM is out, are you going to consider supporting Swift 2.3?

**Comment by jflinter** [comment]
Dwifft has been migrated to Swift 3, so this PR won't be necessary anymore. Thanks anyway @regynald !

**Pull request closed without merging**
