### PR TITLE
Reload data if no changes are found

### PR DESCRIPTION
**Pull request by 3lvis**
We were having an issue with updating cells and found that this might be a good workaround for supporting reloading updated cells.

### CODE REVIEW

**Comment by jflinter** [comment]
I think the issue you're having lies elsewhere in your code, and this will introduce unexpected/undesired behavior for other users. Thanks for the PR, but I'm going to close this.

**Comment by 3lvis** [comment]
Hi @jflinter, 

Do you mean that this part of the library handles updates as well? I didn't got that working.

You can find here the example of the non-working demo. If you remove this workaround then updating doesn't work.

https://github.com/TheSwiftAlps/CounterExample

**Comment by 3lvis** [comment]
Hi @jflinter, 

Do you mean that this part of the library handles updates as well? I didn't got that working.

You can find here the example of the non-working demo. If you remove this workaround then updating doesn't work.

https://github.com/TheSwiftAlps/CounterExample

**Comment by jack-stripe** [comment]
If there is no diff between your original array and your updated array, the table view won't be updated. The diff itself is calculated by comparing elements in each array via `==`. So I suggest modifying the implementation of `==` for the elements in your array so that your desired updates will be triggered.

**Comment by 3lvis** [comment]
I think this might just not be possible with  Dwifft. Looks like the UIKit extension only does inserts and deletes, not updates.

**Comment by sahandnayebaziz** [comment]
This is true. If the elements of your diff are recognizably the same by whatever their `Equatable` is, Dwifft will do nothing (which is great, because not everybody wants it to reload everything). You should just add code to your app to run through the cells and do whatever you do in the case that you did get "new" data that didn't need a row diff.

Something like...

```swift
tableView.visibleCells.forEach { cell in
   cell.set(for: [thing in my data source]) 
}
```

**Pull request closed without merging**
