### PR TITLE
Updated project to Swift 3.0

### PR DESCRIPTION
**Pull request by jameshurst**

### CODE REVIEW

**Comment by jflinter** [comment]
Thanks @jameshurst - in the interest of my sanity, I'm not going to merge this until Xcode 8 goes GM.

**Comment by cuva** [comment]
Any chance we can get that merged now that Xcode 8 went GM?

**Comment by jflinter** [comment]
@jameshurst - can you update your PR to specify `osx_image: xcode8` at the top of .travis.yml? I'd like to make sure CI works before merging this to master.

**Comment by jameshurst** [comment]
@jflinter I've run the Swift migrator on the example application and updated .travis.yml.

**Comment by jflinter** [comment]
Thanks @jameshurst - it looks like the new Travis Xcode VMs have some weird keychain issues; I'll try and figure them out over the weekend and merge this once I do.

**Comment by jflinter** [comment]
Hey @jameshurst - will you give me permission to push to your fork, using github's [new fork collaboration option](https://github.com/blog/2247-improving-collaboration-with-forks)? It'll be easier for me to figure out these Travis issues, and I'd like to see how the new fork thing works anyway : P

**Comment by jameshurst** [comment]
@jflinter that should be enabled now

**Comment by jflinter** [comment]
Had to make some CI fixes, but this is now merged. Thanks @jameshurst !

**Pull request merged**
